---
plugin: yc_compute
folders:
  - b1g3ev1fmlsskdbgvue4
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: ~/Otus/key.json
compose:
 ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address

groups:
 db: labels['tags'] == 'reddit-db'
 app: labels['tags'] == 'reddit-app'
