---
- name: Configure hosts and deploy application
  hosts: default
  become: yes

  roles:
    - app
    - jdauphant.nginx

# - name: Install Ruby && Bundler
#   hosts: all
#   become: true
#   tasks:
#   # Установим в цикле все зависимости
#   - name: Install ruby and rubygems and required packages
#     apt: "name={{ item }} state=present"
#     with_items:
#       - ruby-full
#       - ruby-bundler
#       - build-essential
#       - git
