plugin: community.general.yc_compute
folders:
  - b1g3ev1fmlsskdbgvue4
auth_kind: serviceaccountfile
service_account_file: ~/Otus/key.json
# You can also format hostnames with jinja2 expressions like this
# - "{{id}}_{{name}}"
compose:
  # Set ansible_host to the Public IP address to connect to the host.
  # For Private IP use "network_interfaces[0].primary_v4_address.address".
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
keyed_groups:
  - key: labels['group']
'''
